CREATE TABLE IF NOT EXISTS CLIENT (
    ID_CLIENT BIGINT PRIMARY KEY NOT NULL,
    NM_CLIENT VARCHAR NOT NULL,
    TP_GENDER VARCHAR NOT NULL,
    DT_BIRTH_DAY DATE NOT NULL,
    ID_ADDRESS BIGINT NOT NULL,
    CONSTRAINT fk_address
    FOREIGN KEY(ID_ADDRESS)
    REFERENCES ADDRESS(ID_ADDRESS)
);

CREATE SEQUENCE IF NOT EXISTS SEQ_CLIENT
INCREMENT 1
START 1
OWNED BY CLIENT.ID_CLIENT;

CREATE INDEX IDX_ADDRESS
ON CLIENT (ID_ADDRESS);

ALTER TABLE CLIENT
ADD CONSTRAINT TYPE_GENDER
CHECK (TP_GENDER IN (
    'MALE',
    'FEMALE'
));