INSERT INTO ADDRESS (ID_ADDRESS, DS_STATE, DS_CITY) VALUES( NEXTVAL('seq_address'), 'PE', 'Recife');
INSERT INTO ADDRESS (ID_ADDRESS, DS_STATE, DS_CITY) VALUES( NEXTVAL('seq_address'), 'SP', 'São Paulo');
INSERT INTO ADDRESS (ID_ADDRESS, DS_STATE, DS_CITY) VALUES( NEXTVAL('seq_address'), 'RJ', 'Rio de Janeiro');