INSERT INTO CLIENT (ID_CLIENT, NM_CLIENT, TP_GENDER, DT_BIRTH_DAY, ID_ADDRESS) VALUES( NEXTVAL('sequence_client'), 'José Silva', 'MALE', '1990-01-01', 1);
INSERT INTO CLIENT (ID_CLIENT, NM_CLIENT, TP_GENDER, DT_BIRTH_DAY, ID_ADDRESS) VALUES( NEXTVAL('sequence_client'), 'Carla Souza', 'FEMALE', '1995-01-01', 1);
INSERT INTO CLIENT (ID_CLIENT, NM_CLIENT, TP_GENDER, DT_BIRTH_DAY, ID_ADDRESS) VALUES( NEXTVAL('sequence_client'), 'Armando Brito', 'MALE', '2000-01-01', 2);
INSERT INTO CLIENT (ID_CLIENT, NM_CLIENT, TP_GENDER, DT_BIRTH_DAY, ID_ADDRESS) VALUES( NEXTVAL('sequence_client'), 'Ana Maria', 'FEMALE', '2005-01-01', 2);
INSERT INTO CLIENT (ID_CLIENT, NM_CLIENT, TP_GENDER, DT_BIRTH_DAY, ID_ADDRESS) VALUES( NEXTVAL('sequence_client'), 'Enzo Fernandes', 'MALE', '2010-01-01', 3);
INSERT INTO CLIENT (ID_CLIENT, NM_CLIENT, TP_GENDER, DT_BIRTH_DAY, ID_ADDRESS) VALUES( NEXTVAL('sequence_client'), 'Renata Nunes', 'FEMALE', '2010-01-01', 3);